### ISSUE TITLE
pullInterval

### ISSUE THREAD

**Issue by nchlsgh1** [Supereg/homebridge-http-humidity-sensor#1]
Hi Andi,
Not sure on the humidity characteristic but can we also set an optional pullInterval for this?

I'm using this to measure water tank level and it's already reporting in 0-100 but not sure if there is an auto update interval.

Not an issue... but a request
Cheers :)

**Comment by bauer-andreas** [comment]
It is not implemented yet. I’m currently expanding on the http switch. After that I put some work into streamlining all features of my homebridge-http-* repositories :)

**Comment by bauer-andreas** [comment]
Added `pullInterval` property into v0.1.4 which was publish right now.

**Comment by nchlsgh1** [comment]
This is great work! Thanks Andi! 

Btw this is used for my aquarium
-switch to control the lightings/chiller/pump and 
-humidity for the 0-100% tanks water levels 

It's perfect now :)
