### ISSUE TITLE
Notification characteristic value not matching correctly

### ISSUE THREAD

**Issue by jmchardy** [Supereg/homebridge-http-humidity-sensor#3]
When sending notifications to the notification server for humidity or temperature the documentation guidance is to set the characteristic to "CurrentRelativeHumidity" or "CurrentTemperature" (for the homebridge-http-temperature-sensor). Prior to the refactor for MQTT support ( < v1 ) this worked as the call to 
this.homebridgeService.testCharacteristic(body.characteristic) (index.js-v1.0.3 line 121) was not made and instead the setCharacteristic call was made with characteristic set to Characteristic.CurrentRelativeHumidity (index.js-v0.1.6 line 92 after being set in line 84).

testCharacteristic("CurrentRelativeHumidity") returns **false**, however testCharacteristic("Current Relative Humidity") returns **true**.

When I refactored my Notification POST to send the Humidy characteristic as "Current Relative Humidity" it updates the value, but when set to "CurrentRelativeHumidity" i receive the following error:
Encountered unknown characteristic when handling notification (or characterisitic which wasn't added to the service): CurrentRelativeHumidity 
and the humidity isn't updated. This is caused by testCharacteristic returning false.

The same issue exists in homebridge-http-temperature-sensor.
PR for Review to potentially correct this (tested): #2 

homebridge@0.4.50
homebridge-http-notification-server@1.0.7
homebridge-http-humidity-sensor@1.0.3
homebridge-http-temperature-sensor@1.0.5
hap-nodejs@0.4.53
node v12.5.1
npm 6.10.3
mac osx 10.14.2

**Comment by bauer-andreas** [comment]
Pushed v1.0.4 (and v1.0.6 for homebridge-http-temperature-sensor) which fixes that issue
